### ISSUE TITLE
Require $system_code variable be set by consumers of this component

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/o-footer-services#10]
We have a lot of origami-image-service requests with source=o-icons, which is actually not useful as we don't know who the real source is. E.G. Is it HTSI/FT/NAR/ScoutAsia?

This is due to the fact that the origami components hardcode a source value in their scss. E.G. https://github.com/Financial-Times/o-footer-services/blob/7741e60c2957f1e3723ba3b9d5dd6874025af687/src/scss/_mixins.scss#L118

I'm thinking when we introduce source= to the Origami-Build-Service, we update the origami components to require users pass in a $source or $system_code variable in order to use them. We can then use the $system_code/$source as the value passed to the origami-image-service URLs within the scss.

Waiting on Financial-Times/origami-build-service#67

**Comment by notlee** [comment]
We're going for `$system-code`, with a dash

**Comment by notlee** [comment]
Closing as it's completed in the breaking branch, and it's easier to keep track of progress this way.
